server:
  port: 8082
spring:
  application:
    name: comment
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
