server:
  port: 8085
spring:
  application:
    name: serverclient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
